org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Default alamat server Django (bisa diubah dari layar login aplikasi).
# Emulator Android: http://10.0.2.2:8000/  | HP: http://<ip-lan-server>:8000/
tteApiBaseUrl=https://simrs.rsiyatofa.co.id/
tteApiKey=rahasia123
